--- #YAML:1.0
name:               LWP-ConnCache-MaxKeepAliveRequests
version:            0.33
abstract:           A connection cache that enforces a max keep alive limit
author:
    - Leon Brocard <acme@astray.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    LWP:    0
    Moose:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
